version: "3.7" # 파일 규격 버전
volumes:
  dbdata: # 볼륨 명칭 : docker_dbdate
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의 ( 컴포즈에서 컨테이너 : 서비스 )
  db: # 서비스 명
    #### mysql 이미지
    image: mysql:5.7 # 사용할 이미지
    restart: always
    container_name: mysql-myway-test # 컨테이너 이름 설정
    ports:
      - "3309:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
    environment: # -e 옵션
      - MYSQL_DATABASE=myspring
      - MYSQL_USER=spring
      - MYSQL_PASSWORD=book
      - MYSQL_ROOT_PASSWORD=1234  # MYSQL 루트 패스워드 설정 옵션
      - TZ=Asia/Seoul

    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - dbdata:/var/lib/mysql2 # -v 옵션 (다렉토리 마운트 설정)

  # POSTGRESQL 이미지.
  postrgesqldb:
    image: "postgres:alpine"
    container_name: myway-postgresql
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./postgresql/data:/var/lib/postgresql/data
      - dbdata:/var/lib/postgresql
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_PASSWORD=book
      - POSTGRES_USER=spring
      - POSTGRES_DB=myspring
      - TZ= "Asia/Seoul"