# docker-compose.yml
version: '3'
services:
  postgresql:
    image: postgres
    container_name: myway-postgresql
#    restart: always
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSGRES_DB: myspring
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: book
      TZ: "Asia/Seoul"